n1=[10,20,30,40,50]
n2=[60,70]
n3=n1.extend(n2)
print("after adding :::",n1)
n1.pop()
print("after calling pop :::",n1)
n1.remove(60)
print("after calling pop :::",n1)
n1.sort()
print("after calling pop :::",n1)
print("after calling pop accseniding:::",n1)
n1.sort()
print("after calling sort decseniding :::",n1)
print("after calling sort accseniding :::",n1)
n1.sort(reverse=True)
print("after calling sort accseniding :::",n1)
n1.insert(3,"280")
print("after calling insert function :::",n1)
n2.clear()
print("after calling clear function :::",n2)
